name: Pull upstream
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: upstream
          fetch-depth: 10
      - name: Pull upstream
        run: |
          git remote add upstream 'https://git.door43.org/unfoldingWord/en_ult.git'
          git pull --ff-only upstream master
          git push origin master
